name: tenants

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - PGDATABASE=railway
      - PGUSER=postgres
      - PGPASSWORD=gvnEctLRqTYMViLUylnYdeibdKHrlUXg
      - PGHOST=centerbeam.proxy.rlwy.net
      - PGPORT=18589
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: