name: tenants

services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: Ayomide
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: